/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-115973-g127545350f-20240622"
#endif /* AVUTIL_FFVERSION_H */
